update slackbuild directory (README, doinst.sh, slack-desc, spman.SlackBuild)

diff --git a/slackbuild/spman.SlackBuild b/slackbuild/spman.SlackBuild
--- a/slackbuild/spman.SlackBuild
+++ b/slackbuild/spman.SlackBuild
@@ -1,88 +1,120 @@
 #!/bin/sh
 
-# Buiding package spman for Slackware linux
-# Author: MyRequiem
+# Slackware build script for spman
+#
+# spman - Slackware package manager
+# Home page: https://github.com/MyRequiem/spman
+#
+# Copyright (c) 2018 Vladimir MyRequiem Astrakhan, Russia
+# <mrvladislavovich@gmail.com>
+# All rights reserved
 
-if [ "$(id -u)" != "0" ]; then
-    echo "${PKGNAME}.SlackBuild script can only be run as root."
-    exit
-fi
+# Redistribution and use of this script, with or without modification, is
+# permitted provided that the following conditions are met:
+#
+# 1. Redistributions of this script must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
+# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
+# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
+# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
+# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
+# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
+# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
+# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-PKGNAME="spman"
+
+PRGNAM=spman
 VERSION="$(grep "self.prog_version = " ../src/maindata.py | cut -d \' -f 2)"
-CWD="$(pwd)"
-TMP="/tmp"
-PKG="${TMP}/${PKGNAME}-build"
-BUILD="1"
-TAG="myreq"
-PKGTYPE="txz"
-OUTPUT="${TMP}"
+BUILD=${BUILD:-1}
+TAG=${TAG:-_myreq}
 
-MARCH="$(uname -m)"
-if [[ "x${ARCH}" == "x" ]]; then
-    case "${MARCH}" in
-        i?86) ARCH="i586"       ;;
-        arm*) ARCH="arm"        ;;
-        *)    ARCH="${MARCH}"   ;;
-    esac
+# Automatically determine the architecture we're building on:
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) ARCH=i586 ;;
+    arm*) ARCH=arm ;;
+        # Unless $ARCH is already set, use uname -m for all other archs:
+       *) ARCH=$( uname -m ) ;;
+  esac
 fi
 
-LIBDIRSUFFIX=""
-[[ "${ARCH}" == "x86_64" ]] && LIBDIRSUFFIX="64"
+CWD=$(pwd)
+TMP=${TMP:-/tmp}
+PKG=$TMP/package-$PRGNAM
+PKGTYPE=${PKGTYPE:-txz}
+OUTPUT=${OUTPUT:-/tmp}
 
-rm -rf "${PKG}"
-mkdir -p "${PKG}"
-cd .. || exit 1
+if [ "$ARCH" = "i586" ]; then
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  LIBDIRSUFFIX="64"
+else
+  LIBDIRSUFFIX=""
+fi
 
-SBIN="${PKG}/usr/sbin"
-mkdir -p "${SBIN}"
-cat "src/${PKGNAME}" > "${SBIN}/${PKGNAME}"
-chmod 744 "${SBIN}/${PKGNAME}"
+set -e
 
-cp -R "./etc" "${PKG}"
+if ! which python3 &>/dev/null; then
+    echo "Error: python3 not found"
+    echo "You must install python3 package from SBo repository"
+    exit 1
+fi
+
+rm -rf $PKG
+mkdir -p $TMP $PKG $OUTPUT
+chown -R root:root ../
+find -L ../ \
+ \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
+  -o -perm 511 \) -exec chmod 755 {} \; -o \
+ \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+
+mkdir -p $PKG/usr/sbin
+install --mode=744 ../src/$PRGNAM $PKG/usr/sbin
+
+# etc/{spman,bash_completion.d}
+cp -R ../etc $PKG
 (
-    cd "${PKG}/etc/${PKGNAME}" || exit 1
+    cd $PKG/etc/$PRGNAM || exit 1
     CONFIGS=$(ls)
-    for CONFIG in ${CONFIGS}; do
-        chmod 644 "${CONFIG}" && mv "${CONFIG}" "${CONFIG}".new
+    for CONFIG in $CONFIGS; do
+        chmod 644 $CONFIG
+        mv $CONFIG $CONFIG.new
     done
 )
-chmod 755 "${PKG}/etc/bash_completion.d/${PKGNAME}-bash-complition.sh"
+chmod 755 $PKG/etc/bash_completion.d/$PRGNAM-bash-complition.sh
 
+# python libs
 PY3VER="$(python3 -V | cut -d ' ' -f 2 | cut -d . -f 1,2)"
-LIBS="${PKG}/usr/lib${LIBDIRSUFFIX}/python${PY3VER}/site-packages/${PKGNAME}"
+LIBS=$PKG/usr/lib$LIBDIRSUFFIX/python$PY3VER/site-packages/$PRGNAM
 mkdir -p "${LIBS}"
-find "./src" -type f -name "*.py" -exec cp {} "${LIBS}" \;
+install --mode=644 ../src/*.py $LIBS
 
-DOCS="${PKG}/usr/doc/${PKGNAME}-${VERSION}"
-mkdir -p "${DOCS}"
-cat "${CWD}"/${PKGNAME}.SlackBuild > "${DOCS}/${PKGNAME}.SlackBuild"
-cp ./{AUTHORS,ChangeLog.txt,INSTALL,LICENSE,requirements.txt} "${DOCS}"
+# copy man pages
+mkdir -p $PKG/usr/man/man8
+cp ../man/$PRGNAM.8 $PKG/usr/man/man8
+# compress man pages
+find $PKG/usr/man -type f -exec gzip -9 {} \;
 
-INSTALL="${PKG}/install"
-mkdir -p "${INSTALL}"
-cat "${CWD}/slack-desc" > "${INSTALL}/slack-desc"
-cat "${CWD}/doinst.sh" > "${INSTALL}/doinst.sh"
+# copy program documentation into the package
+DOCS=$PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -p $DOCS
+cat $CWD/$PRGNAM.SlackBuild > $DOCS/$PRGNAM.SlackBuild
+cat $CWD/README > $DOCS/README
+cp -a ../{AUTHORS,ChangeLog.txt,INSTALL,LICENSE,README.md,requirements.txt} \
+    $DOCS
 
-cd "${PKG}" || exit 1
-chown -R root:root .
-find . \( \
-        -perm 777 -o \
-        -perm 775 -o \
-        -perm 711 -o \
-        -perm 555 -o \
-        -perm 511 \
-    \) -exec chmod 755 {} \; \
-    -o \( \
-        -perm 666 -o \
-        -perm 664 -o \
-        -perm 600 -o \
-        -perm 444 -o \
-        -perm 440 -o \
-        -perm 400 \
-    \) -exec chmod 644 {} \;
+# copy the slack-desc and custom doinst.sh into ./install
+mkdir -p $PKG/install
+cat $CWD/slack-desc > $PKG/install/slack-desc
+cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
-mkdir -p "${OUTPUT}"
-BINPKG="${OUTPUT}/${PKGNAME}-${VERSION}-${ARCH}-${BUILD}_${TAG}.${PKGTYPE}"
-rm -f "${BINPKG}"
-makepkg -l y -c n "${BINPKG}"
+# make the package
+cd $PKG
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
